// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:08a40168-cf3c-445f-a471-bd8908346ceb",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_GNbsDS1xu",
    "aws_user_pools_web_client_id": "7vund3gkv983dhavoqplv68kkt",
    "aws_appsync_graphqlEndpoint": "https://ndizxeyclzek7leoxsaipzzwpu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "jsexam",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://jsexam.s3-website-ap-northeast-1.amazonaws.com"
};


export default awsmobile;
